### ISSUE TITLE
Not compatable with React frontend logging (using next js)

### ISSUE THREAD

**Issue by sheenarbw** [Julien-R44/pino-loki#20] opened 2023-06-01 11:40 UTC
I want to use Loki for frontend log collection.

I have a page that looks like this:

```
export default function TestLogging() {
  logger.debug("client-side debug");
  logger.info("client-side info");
  logger.warn("client-side warn");
  logger.error("client-side error");
  
  useEffect(() => {
    logger.debug("useEffect debug");
    logger.info("useEffect info");
    logger.warn("useEffect warn");
    logger.error("useEffect error");
  }, []);

  return <div>TestLogging</div>;
}

export async function getServerSideProps({ req }) {  
  // for those unfamiliar with Nextjs, this runs on the server before the component gets rendered
  logger.info("server-side info");
  logger.warn("server-side warn");
  logger.error("server-side error");
  return { props: {} };
}
```

The "client-side" and "server-side" logs get to Loki just fine. The "useEffect" logs dont.

If I look at my console in my browser then I can see logs for the client side logs and the useEffect logs, so those lines are definately executing. 

Here's another problem, I think it is related:

I have an ErrorBoundary component that looks very standard:

```
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }
  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    logger.info({ error, errorInfo }, "componentDidCatch info");
    logger.error({ error, errorInfo }, "componentDidCatch error");
  }

  render() {
    if (this.state.hasError) {
      logger.info("Error Fallback here");
      return <ErrorBoundaryFallback />;
    }

    // Return children components in case of no error
    logger.info("This is the only log that works");  #########

    return this.props.children;
  }
}
```

Nothing gets logged to Loki when there is an error. It only logs if there are no errors at all.

**Comment by Julien-R44** [comment] 2023-06-01 12:51
I'm not at all familiar with React or Next.js, so it might be a bit complicated for me to help you

Could you provide a reproduction repo please? That would help me see things more clearly. And also the config you use for pino and also pino-loki

**Comment by Julien-R44** [comment] 2023-06-01 22:13
Let me know if you find a solution! I built this library with only backend in mind, however I know pino can be used on the frontend but I've never used it in this context. So we may need some adjustements to make pino-loki works with webapps

I'll try to find the time this weekend to test it on a web app

**Comment by Julien-R44** [comment] 2023-10-10 21:19
Closing since not really actionnable

Feel free to re-open with more details if needed !

**Closed by Julien-R44** 2023-10-10 21:19 UTC
Labels: question
