### ISSUE TITLE
Issues pushing to Loki Distributed

### ISSUE THREAD

**Issue by Sam-Sundar** [Julien-R44/pino-loki#24] opened 2024-01-16 10:29 UTC
We've moved away from Loki Simple Scalable to [Loki-Distributed](https://artifacthub.io/packages/helm/grafana/loki-distributed)  which has below components. 

```
 kubectl get svc -n loki
NAME                                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
loki-distributed-compactor                 ClusterIP   10.72.7.5      <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-distributor               ClusterIP   10.72.1.114    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-gateway                   ClusterIP   10.72.10.158   <none>        80/TCP                       5d3h
loki-distributed-ingester                  ClusterIP   10.72.5.141    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-ingester-headless         ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-memberlist                ClusterIP   None           <none>        7946/TCP                     5d3h
loki-distributed-querier                   ClusterIP   10.72.5.210    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-querier-headless          ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-query-frontend            ClusterIP   10.72.6.150    <none>        3100/TCP,9095/TCP,9096/TCP   5d3h
loki-distributed-query-frontend-headless   ClusterIP   None           <none>        3100/TCP,9095/TCP,9096/TCP   5d3h
loki-distributed-query-scheduler           ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
```

Here `loki-distributed-gateway` is a nginx proxy which sends requests based on url subpath. We tried to configure pino to push to `loki-distributed-gateway` , `loki-distributed-ingester` & `loki-distributed-distributor` and we are getting below error
`Got error when trying to send log to Loki: Response code 400 (Bad Request)`. 

If we add [/loki/api/v1/push](https://grafana.com/docs/loki/latest/reference/api/#push-log-entries-to-loki) to the endpoint, pino starts throwing 404 like below.
`Got error when trying to send log to Loki: Response code 404 (Not Found)`

PS: Also attaching my promtail config, which is able to push to Loki Distributed without any issues. 
`promtail.yaml`
```yaml
server:
  log_level: info
  http_listen_port: 3101
  

clients:
  - url: http://loki-distributed-gateway.loki/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_release
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: instance
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
  
  

limits_config:
```

CC: @Gab-Metzger

**Comment by Julien-R44** [comment] 2024-01-16 12:41
i'm not at all familiar with Loki Distributed so not sure if i can help here

You should try to push a log manually ( via postman for example ) and see if it works. then, we'll know if we need to make any particular changes to `pino-loki`

**Comment by Sam-Sundar** [comment] 2024-01-16 12:58
@Julien-R44,

curl request works without any issues.
![image](https://github.com/Julien-R44/pino-loki/assets/83000807/ab033403-3743-4847-865c-1e05d251f3ef)

```bash
curl -v -H "Content-Type: application/json" -XPOST -s "http://loki-distributed-gateway.loki/loki/api/v1/push" --data-raw '{"streams": [{"stream": {"test": "workspace-backend-test"}, "values":  [["'$(date -u +"%s%N")'", "Testing Logs"]]}]}'
```

**Comment by Julien-R44** [comment] 2024-01-16 13:07
i think the ideal would be for you to tweak pino-loki directly in your node_modules to see what's wrong 

otherwise, you will need to provide a reproduction repo with the setup needed to run loki distributed locally

**Comment by Gab-Metzger** [comment] 2024-01-18 10:44
Hi Julien,

I was able to identify the origin of the issue.
I'm using the `propsToLabel` option to be able to parse and filter my log payload directly in Loki.
I'm getting the 400 Bad request error only if I define the following properties inside the `propsToLabel` option:
- statusCode
- duration
- ip
- userId

This is not working:
```
propsToLabels: [
        'requestId',
        'scope',
        'msg',
        'method',
        'path',
        'statusCode',
        'duration',
        'ip',
        'userId',
        'sentryEventId'
]
```

But this is working:
```
propsToLabels: [
        'requestId',
        'scope',
        'msg',
        'method',
        'path',
        // 'statusCode',
        // 'duration',
        // 'ip',
        // 'userId'
        'sentryEventId'
]
```

Am I using this option correctly?

**Comment by Julien-R44** [comment] 2024-01-18 14:28
Yeah that look good to me. Is it only when you remove those 4 properties that it works? Or is it just one of them that makes everything crash?  

On a side note, i would recommend avoiding using these properties as labels. Anything with a high cardinality should, in theory, not be used as a label. See https://grafana.com/docs/loki/latest/get-started/labels/bp-labels/

They're talking specifically about `requestId` here, but I'd say even `duration` and `ip` shouldn't be labels

> This is a perfect example of something which should not be a label, requestId should be removed as a label and instead filter expressions should be used to query logs for a specific requestId. For example if requestId is found in the log line as a key=value pair you could write a query like this: {logGroup="group1"} |= "requestId=32422355"

**Comment by Gab-Metzger** [comment] 2024-01-18 14:30
No all 4 are causing issues.

Got your side note, I'll avoid using them as labels.

**Comment by Julien-R44** [comment] 2024-04-27 23:44
Closing since not actionnable

**Closed** 2024-04-27 23:45 UTC
Labels: question
